title: Ajeet Singh
url: "https://ajeetsingh.me"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Selected Works"
   link: "research"
 - name: "CarePraxis"
   link: "CarePraxis"
 - name: "Contact"
   link: "contact"
